services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    # .env faylidagi o'zgaruvchilarni yuklash
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - taxi_network

  telegram-bot:
    build: .
    container_name: telegram_bot
    restart: always
  
    environment:
      # Docker-compose o'zgaruvchilarni mana shunday formatda birlashtira oladi:
      DATABASE_URL: "postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
    volumes:
      - .:/app

volumes:
  postgres_data:

networks:
  taxi_network:
    driver: bridge