"""initial migration

Revision ID: 0001_initial
Revises: 
Create Date: 2026-02-01 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('fullname', sa.String(), nullable=True),
        sa.Column('phone', sa.Integer(), nullable=True),
        sa.Column('telegram_id', sa.BigInteger(), nullable=True, unique=True)
    )

    op.create_table('regions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('region_name', sa.String(), nullable=True)
    )

    op.create_table('condition',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(), nullable=True)
    )

    op.create_table('requests',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id')),
        sa.Column('from_region', sa.Integer(), sa.ForeignKey('regions.id')),
        sa.Column('to_region', sa.Integer(), sa.ForeignKey('regions.id')),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('number_of_people', sa.Integer(), nullable=True),
        sa.Column('condition_id', sa.Integer(), sa.ForeignKey('condition.id'))
    )

    op.create_table('complaints',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('info', sa.String(), nullable=True)
    )

    op.create_table('user_taxi',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('fullname', sa.String(), nullable=True),
        sa.Column('nomer', sa.Integer(), nullable=True),
        sa.Column('car_model', sa.String(), nullable=True),
        sa.Column('car_nomer', sa.Integer(), nullable=True),
        sa.Column('telegram_id', sa.BigInteger(), nullable=True)
    )

    op.create_table('users_taxi',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('nomer', sa.Integer(), nullable=True),
        sa.Column('car_model', sa.String(), nullable=True),
        sa.Column('car_nomer', sa.Integer(), nullable=True),
        sa.Column('telegram_id', sa.BigInteger(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_taxi')
    op.drop_table('user_taxi')
    op.drop_table('complaints')
    op.drop_table('requests')
    op.drop_table('condition')
    op.drop_table('regions')
    op.drop_table('users')
    # ### end Alembic commands ###
