# """fix

# Revision ID: 49e48b08518a
# Revises: b817acb78f33
# Create Date: 2026-03-31 07:18:19.970355

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = '49e48b08518a'
# down_revision: Union[str, Sequence[str], None] = 'b817acb78f33'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('taxi', 'telegram_id',
#                existing_type=sa.VARCHAR(),
#                type_=sa.BIGINT(),
#                existing_nullable=True)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('taxi', 'telegram_id',
#                existing_type=sa.BIGINT(),
#                type_=sa.VARCHAR(),
#                existing_nullable=True)
#     # ### end Alembic commands ###


from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '49e48b08518a'
down_revision = 'b817acb78f33'  # oldingi migration id sini yoz
branch_labels = None
depends_on = None

def upgrade():
    op.execute(
        "ALTER TABLE taxi ALTER COLUMN telegram_id TYPE BIGINT USING telegram_id::bigint;"
    )

def downgrade():
    op.execute(
        "ALTER TABLE taxi ALTER COLUMN telegram_id TYPE VARCHAR USING telegram_id::varchar;"
    )