"""User table has been updated

Revision ID: 74ff2d59dd11
Revises: 279043d0b3a8
Create Date: 2026-04-27 19:40:36.143758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ff2d59dd11'
down_revision: Union[str, Sequence[str], None] = '279043d0b3a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'phone')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_used_at')
    # ### end Alembic commands ###
