"""fix

Revision ID: f9fa625660d9
Revises: 1d949871f2cb
Create Date: 2026-04-15 13:29:19.657217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fa625660d9'
down_revision: Union[str, Sequence[str], None] = '1d949871f2cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('location_message_id', sa.BIGINT(), nullable=True))
    op.add_column('orders', sa.Column('driver_id', sa.BIGINT(), nullable=True))
    op.add_column('orders', sa.Column('chat_id', sa.BIGINT(), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('resent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'resent')
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'chat_id')
    op.drop_column('orders', 'driver_id')
    op.drop_column('orders', 'location_message_id')
    op.drop_column('orders', 'lon')
    op.drop_column('orders', 'lat')
    # ### end Alembic commands ###
